name: ⏯️ Generate pre-release PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease:
    uses: ./.github/workflows/shared_create_prerelease_pr.yml
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PK }}

