name: ⏯️ Generate Pre-Release PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prerelease:
    uses: ./.github/workflows/shared_create_prerelease_pr.yml
    # uses: newrelic/newrelic-agent-control/.github/workflows/shared_create_prerelease_pr.yml@main
