name: on_prerelease
on:
  release:
    types:
      - prereleased
permissions:
  contents: read
jobs:
  check-version:
    runs-on: ubuntu-latest
    name: Check version in Cargo.toml
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Check if Cargo.toml version matches pre-release tag
        run: |
          NEWRELIC_AUTH_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
          if [ "${NEWRELIC_AUTH_VERSION}" != "${{ github.event.release.tag_name }}" ]; then
            echo "Package version specified in Cargo.toml (${NEWRELIC_AUTH_VERSION}) differs from tag (${{ github.event.release.tag_name }}), exiting"
            exit 1
          fi
